/* Generated By:JJTree: Do not edit this line. ASTMerge.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ParfANode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMerge extends SimpleNode {
  public ASTMerge(int id) {
    super(id);
  }

  public ASTMerge(ParfA p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=46ec5a4f56d3daabf0cdba1ce2286cba (do not edit this line) */
