/* Generated By:JJTree: Do not edit this line. ASTVariableType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ParfANode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableType extends SimpleNode {
  public ASTVariableType(int id) {
    super(id);
  }

  public ASTVariableType(ParfA p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=759e6eb1a5a5f82316bd84492fff6b30 (do not edit this line) */
