/* Generated By:JavaCC: Do not edit this line. ParfATreeConstants.java Version 5.0 */
public interface ParfATreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTEQUALS = 4;
  public int JJTNOTEQUALS = 5;
  public int JJTLESSTHAN = 6;
  public int JJTGREATERTHAN = 7;
  public int JJTLESSTHANOREQUALTO = 8;
  public int JJTGREATERTHANOREQUALTO = 9;
  public int JJTADD = 10;
  public int JJTSUBTRACT = 11;
  public int JJTMULTIPLY = 12;
  public int JJTDIVIDE = 13;
  public int JJTMODULUS = 14;
  public int JJTNOT = 15;
  public int JJTNUMBEROF = 16;
  public int JJTCONTAINS = 17;
  public int JJTNUMBERLITERAL = 18;
  public int JJTLOGICLITERAL = 19;
  public int JJTTEXTLITERAL = 20;
  public int JJTLISTLITERAL = 21;
  public int JJTID = 22;
  public int JJTANSWER = 23;
  public int JJTIFSTATEMENT = 24;
  public int JJTLOOPSTATEMENT = 25;
  public int JJTREPEATUNTILSTATEMENT = 26;
  public int JJTFOREVERSTATEMENT = 27;
  public int JJTWAITSTATEMENT = 28;
  public int JJTWAITUNTILSTATEMENT = 29;
  public int JJTANNOUNCESTATEMENT = 30;
  public int JJTASKSTATEMENT = 31;
  public int JJTLISTADDSTATEMENT = 32;
  public int JJTLISTREMOVESTATEMENT = 33;
  public int JJTVARIABLEDECLARESTATEMENT = 34;
  public int JJTVARIABLEASSIGNSTATEMENT = 35;
  public int JJTVARIABLEDECLAREASSIGNSTATEMENT = 36;
  public int JJTBLOCK = 37;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "Or",
    "And",
    "Equals",
    "NotEquals",
    "LessThan",
    "GreaterThan",
    "LessThanOrEqualTo",
    "GreaterThanOrEqualTo",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "Modulus",
    "Not",
    "NumberOf",
    "Contains",
    "NumberLiteral",
    "LogicLiteral",
    "TextLiteral",
    "ListLiteral",
    "Id",
    "Answer",
    "IfStatement",
    "LoopStatement",
    "RepeatUntilStatement",
    "ForeverStatement",
    "WaitStatement",
    "WaitUntilStatement",
    "AnnounceStatement",
    "AskStatement",
    "ListAddStatement",
    "ListRemoveStatement",
    "VariableDeclareStatement",
    "VariableAssignStatement",
    "VariableDeclareAssignStatement",
    "Block",
  };
}
/* JavaCC - OriginalChecksum=360c3ddd587f6d4aeaeba062b3dea798 (do not edit this line) */
